from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL")
COVERAGE_RAG_PATH = os.getenv("COVERAGE_RAG_PATH")
COVERAGE_DOC_PATH = os.getenv("COVERAGE_DOC_PATH")
CLAIMS_HISTORY_RAG_PATH = os.getenv("CLAIMS_HISTORY_RAG_PATH")
RAG_INGEST_API_PATH = os.getenv("RAG_INGEST_API_PATH")
RAG_HEALTH_API_PATH = os.getenv("RAG_HEALTH_API_PATH")
RAG_INSPECT_API_PATH = os.getenv("RAG_INSPECT_API_PATH")